Feature/pagination
4alltecnologia/4all-ui pull request #25
Opened 2019-04-09 21:13 UTC by leonardo-alves

2019-04-09 22:15 UTC, mathiasfc approved these changes

2019-04-09 22:15 UTC, mathiasfc commented on src/components/Icons/ArrowPagination/index.js
> +      width={size || '30px'}
Precisa mesmo `|| 30px` ? Já está declarado no default props.

2019-04-10 12:35 UTC, eduardoumpierre requested changes
Concordo com o feedback do Mathias

2019-04-10 14:16 UTC, eduardoumpierre approved these changes

2019-04-10 14:32 UTC, merged

2019-04-10 16:31 UTC, mathiasfc commented on src/components/Icons/ArrowPagination/index.js
> +      width={size || '30px'}
Após conversa, identificamos que existe a possibilidade do usuário passar `undefined || "" || null`, logo é apropriado manter o `|| 30px`